name: navyblue_app
description: "SA Exam Prep with Self-Marking System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Material Design 3 utilities (match Flutter SDK)
  material_color_utilities: ^0.11.1

  # Navigation
  go_router: ^12.1.3

  # Offline First with Brick - FORCE OLDER COMPATIBLE VERSIONS
  brick_offline_first_with_rest: 3.1.0
  brick_rest: 3.1.0
  brick_sqlite: 3.1.0
  
  # Required for Brick
  sqflite: ^2.3.0
  sqflite_common: any
  sqflite_common_ffi_web: any
  sqlite3_flutter_libs: ^0.5.0 
  http: ^1.1.0


  # State Management (Riverpod)
  flutter_riverpod: ^2.4.0

  # Utilities
  json_annotation: ^4.8.1
  uuid: ^4.2.1
  brick_core: ^1.4.0
  file_picker: ^10.3.2
  cached_network_image: ^3.4.1
  flutter_tex: ^5.1.10
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 5.13.0
  flutter_lints: ^3.0.0

  # Code generation for Brick - FORCE OLDER COMPATIBLE VERSIONS
  brick_offline_first_with_rest_build: 3.1.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/flutter_tex.js
    - assets/flutter_tex.css