// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '20250910104207.migration.dart';
part '20250906103617.migration.dart';
part '20250908064003.migration.dart';
part '20250908073957.migration.dart';
part '20250908123137.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{
  const Migration20250910104207(),
  const Migration20250906103617(),
  const Migration20250908064003(),
  const Migration20250908073957(),
  const Migration20250908123137()
};

/// A consumable database structure including the latest generated migration.
final schema = Schema(20250910104207, generatorVersion: 1, tables: <SchemaTable>{
  SchemaTable('ExamPaper', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('title', Column.varchar),
    SchemaColumn('subject', Column.varchar),
    SchemaColumn('grade', Column.varchar),
    SchemaColumn('syllabus', Column.varchar),
    SchemaColumn('year', Column.integer),
    SchemaColumn('exam_period', Column.varchar),
    SchemaColumn('exam_level', Column.varchar),
    SchemaColumn('paper_type', Column.varchar),
    SchemaColumn('province', Column.varchar),
    SchemaColumn('duration_minutes', Column.integer),
    SchemaColumn('instructions', Column.varchar),
    SchemaColumn('total_marks', Column.integer),
    SchemaColumn('is_active', Column.boolean),
    SchemaColumn('uploaded_at', Column.datetime),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('is_favorite', Column.boolean),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar)
  }, indices: <SchemaIndex>{}),
  SchemaTable('PaperFilters', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('subjects', Column.varchar),
    SchemaColumn('grades', Column.varchar),
    SchemaColumn('syllabi', Column.varchar),
    SchemaColumn('years', Column.varchar),
    SchemaColumn('paper_types', Column.varchar),
    SchemaColumn('provinces', Column.varchar),
    SchemaColumn('exam_periods', Column.varchar),
    SchemaColumn('exam_levels', Column.varchar),
    SchemaColumn('updated_at', Column.datetime),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar)
  }, indices: <SchemaIndex>{}),
  SchemaTable('_brick_Question_parts', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('l_Question_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'Question',
        onDeleteCascade: true,
        onDeleteSetDefault: false),
    SchemaColumn('f_QuestionPart_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'QuestionPart',
        onDeleteCascade: true,
        onDeleteSetDefault: false)
  }, indices: <SchemaIndex>{
    SchemaIndex(
        columns: ['l_Question_brick_id', 'f_QuestionPart_brick_id'],
        unique: true)
  }),
  SchemaTable('_brick_Question_solution_steps', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('l_Question_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'Question',
        onDeleteCascade: true,
        onDeleteSetDefault: false),
    SchemaColumn('f_SolutionStep_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'SolutionStep',
        onDeleteCascade: true,
        onDeleteSetDefault: false)
  }, indices: <SchemaIndex>{
    SchemaIndex(
        columns: ['l_Question_brick_id', 'f_SolutionStep_brick_id'],
        unique: true)
  }),
  SchemaTable('Question', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('paper_id', Column.varchar),
    SchemaColumn('question_number', Column.varchar),
    SchemaColumn('context_text', Column.varchar),
    SchemaColumn('context_images', Column.varchar),
    SchemaColumn('topics', Column.varchar),
    SchemaColumn('total_marks', Column.integer),
    SchemaColumn('order_index', Column.integer),
    SchemaColumn('page_number', Column.integer),
    SchemaColumn('question_text', Column.varchar),
    SchemaColumn('hint_text', Column.varchar),
    SchemaColumn('is_active', Column.boolean),
    SchemaColumn('created_at', Column.datetime),
    SchemaColumn('parts', Column.varchar),
    SchemaColumn('solution_steps', Column.varchar),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar),
    SchemaColumn('is_simple_question', Column.boolean),
    SchemaColumn('is_multi_part_question', Column.boolean)
  }, indices: <SchemaIndex>{}),
  SchemaTable('_brick_QuestionPart_solution_steps', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('l_QuestionPart_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'QuestionPart',
        onDeleteCascade: true,
        onDeleteSetDefault: false),
    SchemaColumn('f_SolutionStep_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'SolutionStep',
        onDeleteCascade: true,
        onDeleteSetDefault: false)
  }, indices: <SchemaIndex>{
    SchemaIndex(
        columns: ['l_QuestionPart_brick_id', 'f_SolutionStep_brick_id'],
        unique: true)
  }),
  SchemaTable('_brick_QuestionPart_sub_parts', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('l_QuestionPart_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'QuestionPart',
        onDeleteCascade: true,
        onDeleteSetDefault: false),
    SchemaColumn('f_QuestionPart_brick_id', Column.integer,
        isForeignKey: true,
        foreignTableName: 'QuestionPart',
        onDeleteCascade: true,
        onDeleteSetDefault: false)
  }, indices: <SchemaIndex>{
    SchemaIndex(
        columns: ['l_QuestionPart_brick_id', 'f_QuestionPart_brick_id'],
        unique: true)
  }),
  SchemaTable('QuestionPart', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('question_id', Column.varchar),
    SchemaColumn('parent_part_id', Column.varchar),
    SchemaColumn('part_number', Column.varchar),
    SchemaColumn('part_text', Column.varchar),
    SchemaColumn('marks', Column.integer),
    SchemaColumn('part_images', Column.varchar),
    SchemaColumn('hint_text', Column.varchar),
    SchemaColumn('nesting_level', Column.integer),
    SchemaColumn('order_index', Column.integer),
    SchemaColumn('requires_working', Column.boolean),
    SchemaColumn('is_active', Column.boolean),
    SchemaColumn('created_at', Column.datetime),
    SchemaColumn('solution_steps', Column.varchar),
    SchemaColumn('sub_parts', Column.varchar),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar),
    SchemaColumn('has_sub_parts', Column.boolean),
    SchemaColumn('has_solution_steps', Column.boolean),
    SchemaColumn('total_steps', Column.integer)
  }, indices: <SchemaIndex>{}),
  SchemaTable('SolutionStep', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('part_id', Column.varchar),
    SchemaColumn('question_id', Column.varchar),
    SchemaColumn('step_number', Column.integer),
    SchemaColumn('description', Column.varchar),
    SchemaColumn('working_out', Column.varchar),
    SchemaColumn('marks_for_this_step', Column.integer),
    SchemaColumn('solution_images', Column.varchar),
    SchemaColumn('teaching_note', Column.varchar),
    SchemaColumn('order_index', Column.integer),
    SchemaColumn('is_critical_step', Column.boolean),
    SchemaColumn('created_at', Column.datetime),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar),
    SchemaColumn('belongs_to_part', Column.boolean),
    SchemaColumn('belongs_to_question', Column.boolean)
  }, indices: <SchemaIndex>{}),
  SchemaTable('StepAttempt', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('student_attempt_id', Column.varchar),
    SchemaColumn('step_id', Column.varchar),
    SchemaColumn('status', Column.varchar),
    SchemaColumn('marked_at', Column.datetime),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('is_correct', Column.boolean),
    SchemaColumn('is_incorrect', Column.boolean),
    SchemaColumn('is_not_attempted', Column.boolean)
  }, indices: <SchemaIndex>{}),
  SchemaTable('StudentAttempt', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('paper_id', Column.varchar),
    SchemaColumn('mode', Column.varchar),
    SchemaColumn('enable_hints', Column.boolean),
    SchemaColumn('started_at', Column.datetime),
    SchemaColumn('timer_started_at', Column.datetime),
    SchemaColumn('completed_at', Column.datetime),
    SchemaColumn('last_activity_at', Column.datetime),
    SchemaColumn('total_marks_earned', Column.integer),
    SchemaColumn('total_marks_possible', Column.integer),
    SchemaColumn('percentage_score', Column.Double),
    SchemaColumn('time_spent_minutes', Column.integer),
    SchemaColumn('questions_attempted', Column.integer),
    SchemaColumn('questions_completed', Column.integer),
    SchemaColumn('is_abandoned', Column.boolean),
    SchemaColumn('auto_submitted', Column.boolean),
    SchemaColumn('step_statuses', Column.varchar),
    SchemaColumn('calculated_progress', Column.varchar),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar),
    SchemaColumn('is_completed', Column.boolean),
    SchemaColumn('is_in_progress', Column.boolean),
    SchemaColumn('is_practice_mode', Column.boolean),
    SchemaColumn('is_exam_mode', Column.boolean),
    SchemaColumn('effective_last_activity_at', Column.datetime),
    SchemaColumn('effective_last_synced_at', Column.datetime),
    SchemaColumn('progress_percentage', Column.Double),
    SchemaColumn('marked_steps_count', Column.integer),
    SchemaColumn('correct_steps_count', Column.integer),
    SchemaColumn('calculated_earned_marks', Column.integer),
    SchemaColumn('calculated_possible_marks', Column.integer),
    SchemaColumn('calculated_marked_steps', Column.integer),
    SchemaColumn('calculated_total_steps', Column.integer)
  }, indices: <SchemaIndex>{}),
  SchemaTable('User', columns: <SchemaColumn>{
    SchemaColumn('_brick_id', Column.integer,
        autoincrement: true, nullable: false, isPrimaryKey: true),
    SchemaColumn('id', Column.varchar, unique: true),
    SchemaColumn('email', Column.varchar),
    SchemaColumn('first_name', Column.varchar),
    SchemaColumn('last_name', Column.varchar),
    SchemaColumn('grade', Column.varchar),
    SchemaColumn('province', Column.varchar),
    SchemaColumn('syllabus', Column.varchar),
    SchemaColumn('school_name', Column.varchar),
    SchemaColumn('role', Column.varchar),
    SchemaColumn('is_email_verified', Column.boolean),
    SchemaColumn('created_at', Column.datetime),
    SchemaColumn('access_token', Column.varchar),
    SchemaColumn('refresh_token', Column.varchar),
    SchemaColumn('token_expires_at', Column.datetime),
    SchemaColumn('last_login_at', Column.datetime),
    SchemaColumn('last_synced_at', Column.datetime),
    SchemaColumn('needs_sync', Column.boolean),
    SchemaColumn('device_info', Column.varchar),
    SchemaColumn('full_name', Column.varchar),
    SchemaColumn('is_admin', Column.boolean),
    SchemaColumn('is_token_valid', Column.boolean),
    SchemaColumn('grade_display_name', Column.varchar),
    SchemaColumn('subject_display_name', Column.varchar)
  }, indices: <SchemaIndex>{})
});
